---
Name: dockerlogging
After: '#logging'
---
SilverStripe\Core\Injector\Injector:
  Psr\Log\LoggerInterface:
    calls:
      pushStdoutLogHandler: [ pushHandler, [ '%$StdoutLoggingHandler' ] ]
      pushExtraProcessor: [ pushProcessor, [ '%$ExtraLogProcessor' ] ]
      # pushIntroProcessor: [ pushProcessor, [ '%$IntrospectionHandler' ] ]
  StdoutLoggingHandler:
    class: Monolog\Handler\StreamHandler
    constructor:
      - "php://stdout"
    properties:
      formatter: '%$Monolog\Formatter\JsonFormatter'
  ExtraLogProcessor:
    class: MadeCurious\DockerLogging\ExtraLogProcessor
  # Unused, but this is an example of adding a further monolog processor.
  IntrospectionHandler:
    class: Monolog\Processor\IntrospectionProcessor
